databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: app
    env: ruby
    repo: https://github.com/<your_repo>
    branch: main
    runCommand: bundle exec rackup config.ru
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
